# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-05-09 09:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfile',
            name='all_attributes',
            field=models.TextField(default=datetime.datetime(2020, 5, 9, 9, 37, 27, 257033, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
